name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows-server:
    name: Windows server
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      id: toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-${{ steps.toolchain.outputs.cachekey }}-
    - name: Build aw-server
      run: cargo build -p aw-server --verbose
    - name: Test aw-datastore
      run: cargo test -p aw-datastore --verbose
    - name: Upload Windows server binary
      uses: actions/upload-artifact@v4
      with:
        name: binaries-Windows
        path: target/debug/aw-server.exe
